name: DJANGO CI CD

on:
  pull_request:
    branches: [ "master" ]

jobs:
  CI_CD:
    runs-on: ubuntu-latest
    steps:
      # 깃허브 레포지토리에서 코드를 가져옴
      - name: Checkout
        uses: actions/checkout@v2
      
      # 파이썬 버전 설정
      - name: Set up Python 3.11.0
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0

      # .env 파일 생성
      # 배포시 주석 해제 예정
      
      - name: Setting .env
        run: |
          cd dontworry/config
          echo OPENAI_SECRET_KEY="${{ secrets.OPENAI_SECRET_KEY }}" >> .env
          echo DJANGO_SECRET_KEY="${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo AWS_HOST="${{ secrets.AWS_HOST }}" >> .env
          echo AWS_USERNAME="${{ secrets.AWS_USERNAME }}" >> .env
          echo AWS_KEY_PEM="${{ secrets.AWS_KEY_PEM }}" >> .env
          cd ../..

      # 디펜던시 설치
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 장고 마이그레이션
      - name: Run Migration
        run: |
          cd dontworry
          python manage.py makemigrations
          python manage.py migrate
          cd ..
      
      # Docker Hub에 push할 이미지 빌드
      - name: Docker Build
        run: |
          docker build -t ${{secrets.DOCKER_IMAGE}} .

      # 도커 허브 사용을 위해 도커에 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # 도커 홈페이지에서 발급받은 토큰 사용
      
      - name: Push to DockerHub
        run: |
          docker push ${{secrets.DOCKER_IMAGE}}

      # ssh를 통해 EC2에 접속, 접속한 후에 실행할 스크립트 작성
      - name: Connect to EC2 using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.AWS_HOST}}
          username: ${{secrets.AWS_USERNAME}}
          key: ${{ secrets.AWS_KEY_PEM }}
          envs: GITHUB_SHA
          script: |
            sudo docker-compose down 
            sudo docker-compose pull 
            sudo docker-compose up -d
